#I imported from this program
#This is my header
capital_alpha = {'A': 'APPLE',
                 'B': 'BOX',
                 'C': 'CARROT',
                 'D': 'DOSA',
                 'E': 'END',
                 'F': 'FUNNY',
                 'G': 'GRAPES',
                 'H': 'HI-FI',
                 'I': 'INDIA',
                 'J': 'JAZZ',
                 'K': 'KISS',
                 'L': 'LUCK',
                 'M': 'MAFIA',
                 'N': 'NUCLEAR',
                 'O': 'ORAL',
                 'P': 'PINK',
                 'Q': 'QUEEN',
                 'R': 'RAIN',
                 'S': 'SEX',
                 'T': 'TASTE',
                 'U': 'ULTRA',
                 'V': 'VENDETTA',
                 'W': 'WARM',
                 'X': 'XTREME',
                 'Y': 'YAK',
                 'Z': 'ZIP'}

small_alpha = {'a': 'apple',
               'b': 'box',
               'c': 'carrot',
               'd': 'dosa',
               'e': 'end',
               'f': 'funny',
               'g': 'grapes',
               'h': 'hi-fi',
               'i': 'india',
               'j': 'jazz',
               'k': 'kiss',
               'l': 'luck',
               'm': 'mafia',
               'n': 'nuclear',
               'o': 'oral',
               'p': 'pink',
               'q': 'queen',
               'r': 'rain',
               's': 'sex',
               't': 'taste',
               'u': 'ultra',
               'v': 'vendetta',
               'w': 'warm',
               'x': 'xtreme',
               'y': 'yak',
               'z': 'zip'}

numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

special = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')',
           '<', '>', '{', '}', '[', ']']

